backend:
  name: github
  repo: iywey/iywey.github.io
  branch: main
  auth_endpoint: https://iywey.github.io/admin
  base_url: https://iywey.github.io
  auth:
    client_id: Ov23liwXbccfjDOC48gD
    client_secret: f04bd96f36f2060593749c6ef0ceec775df4114f

media_folder: "assets/images/uploads" # Where images will be stored
public_folder: "/assets/images/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
